POST https://mysql-test-old.apps.espace.lsews.com/accounts
Content-Type: application/json

{}

###
GET https://mysql-test-old.apps.espace.lsews.com/accounts
Accept: application/json

###
GET http://localhost:8080/accounts
Accept: application/json

###
POST http://localhost:8080/accounts
Content-Type: application/json

{}

###



